<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.fog</groupId>
    <artifactId>ifogsim2-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>ifogsim</module>
        <module>ifogsim-examples</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <commons-io.version>2.17.0</commons-io.version>
        <commons-lang3.version>3.17.0</commons-lang3.version>
        <commons-math3.version>3.5</commons-math3.version>
        <commons-net.version>3.11.1</commons-net.version>
        <guava.version>18.0</guava.version>
        <json-simple.version>1.1.1</json-simple.version>
        <opencsv.version>5.9</opencsv.version>
        <geoip2.version>4.2.0</geoip2.version>
        <uncommons-maths.version>1.2.3</uncommons-maths.version>
        <junit-jupiter.version>5.11.3</junit-jupiter.version>
        <easymock.version>5.3.0</easymock.version>
        <surefire.version>3.2.5</surefire.version>
    </properties>
</project>
